modLoader = "javafml"
loaderVersion = "[32,)"
issueTrackerURL = "https://github.com/team-abnormals/buzzier-bees/issues"
license = "https://github.com/team-abnormals/buzzier-bees/blob/main/LICENSE.txt"

[[mods]]
    modId = "buzzier_bees"
    version = "${file.jarVersion}"
    logoFile = "logo.png"
    itemIcon = "buzzier_bees:honey_apple"
    configBackground = "buzzier_bees:textures/block/honeycomb_tiles.png"
    authors = "Team Abnormals"
    credits = "bageldotjpg, five, hatsondogs, Farcr"
    displayURL = "https://www.teamabnormals.com/mods/buzzier-bees"
    displayName = "Buzzier Bees"
    description = '''
    Buzzier Bees expands on the content introduced in 1.15, introducing new building blocks and other honey-related features!
    '''

[[dependencies.buzzier_bees]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.18.2,1.19)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.buzzier_bees]]
    modId = "forge"
    mandatory = true
    versionRange = "[40.1.0,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.buzzier_bees]]
    modId = "blueprint"
    mandatory = true
    versionRange = "[5.4.0,)"
    ordering = "AFTER"
    side = "BOTH"