modLoader = "javafml"
loaderVersion = "[32,)"
issueTrackerURL = "https://github.com/team-abnormals/buzzier-bees/issues"
license = "https://github.com/team-abnormals/buzzier-bees/blob/main/LICENSE.txt"

[[mods]]
    modId = "buzzier_bees"
    version = "${file.jarVersion}"
    logoFile = "logo.png"
    itemIcon = "buzzier_bees:candle"
    configBackground = "buzzier_bees:textures/block/honeycomb_tiles.png"
    authors = "Team Abnormals"
    credits = "bageldotjpg, five, hatsondogs, Farcr"
    displayURL = "https://www.teamabnormals.com/mods/buzzier-bees"
    displayName = "Buzzier Bees"
    description = '''
    Buzzier Bees expands on the content introduced in 1.15, introducing candles, new building blocks, and more!
    '''

[[dependencies.buzzier_bees]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.16.5,1.17)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.buzzier_bees]]
    modId = "forge"
    mandatory = true
    versionRange = "[36.2.0,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.buzzier_bees]]
    modId = "abnormals_core"
    mandatory = true
    versionRange = "[3.2.0,)"
    ordering = "AFTER"
    side = "BOTH"